name: gemini_seg
channels:
  - conda-forge
dependencies:
  # ---- core stack ----
  - python=3.11          # keep in sync with vscode interpreter
  - numpy
  - scikit-image
  - matplotlib
  - pillow
  - pyyaml
  - scikit-learn
  - scikit-posthocs
  - python-dotenv
  - pingouin
  - pandas
  - pyarrow
  - cliffs_delta
  - opencv-python
  # ---- utilities ----
  - jupyterlab           # optional; comment out if not needed
  - ipywidgets
  # ---- PiP-only packages ----
  - pip
  - pip:
      - google-genai   # Gemini API client. google-generativeai is now deprecated
      - replicate
      - moondream
      - cairosvg
      - python-docx
